<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

        <!-- NuGet-specific metadata -->
        <PackageId>Odalith.FFaudio</PackageId>
        <Version>1.0.0</Version>
        <Authors>Odalith,FFmpeg</Authors>
        <Description>Play audio with FFmpeg and SDL2 in dotnet</Description>
        <PackageTags>audio media music playback ffmpeg sdl2</PackageTags>
        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    </PropertyGroup>

</Project>
